POST http://localhost:3005/register/
Content-Type: application/json

{
  "username": "balu_kotthuru",
  "password": "Balu@143",
  "name": "Balu Kotthuru",
  "gender": "male"
}
###

POST http://localhost:3005/login/
Content-Type: application/json

{
  "username": "balu_kotthuru",
  "password": "Balu@143"
}
###

GET http://localhost:3005/user/tweets/feed/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJhbHVfa290dGh1cnUiLCJpYXQiOjE2NzgxNjAyMzd9.35O7EfIYtQ6aRicuDTR_P5WWdgKeIOdznrLz9OsRc_Q
###

GET http://localhost:3005/user/following/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJhbHVfa290dGh1cnUiLCJpYXQiOjE2NzgxNjAyMzd9.35O7EfIYtQ6aRicuDTR_P5WWdgKeIOdznrLz9OsRc_Q
###

GET http://localhost:3005/tweets/4/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJhbHVfa290dGh1cnUiLCJpYXQiOjE2NzgxNjAyMzd9.35O7EfIYtQ6aRicuDTR_P5WWdgKeIOdznrLz9OsRc_Q
###

GET http://localhost:3005/tweets/1/likes/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJhbHVfa290dGh1cnUiLCJpYXQiOjE2NzgxNjAyMzd9.35O7EfIYtQ6aRicuDTR_P5WWdgKeIOdznrLz9OsRc_Q
###

GET http://localhost:3005/tweets/3/replies/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJhbHVfa290dGh1cnUiLCJpYXQiOjE2NzgxNjAyMzd9.35O7EfIYtQ6aRicuDTR_P5WWdgKeIOdznrLz9OsRc_Q
###

GET http://localhost:3005/user/tweets/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJhbHVfa290dGh1cnUiLCJpYXQiOjE2NzgxNjAyMzd9.35O7EfIYtQ6aRicuDTR_P5WWdgKeIOdznrLz9OsRc_Q
###

POST http://localhost:3005/user/tweets/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJhbHVfa290dGh1cnUiLCJpYXQiOjE2NzgxNjAyMzd9.35O7EfIYtQ6aRicuDTR_P5WWdgKeIOdznrLz9OsRc_Q
Content-Type: application/json

{
   "tweet": "Balu The Good Boy"
}
###

DELETE http://localhost:3005/tweets/2/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJhbHVfa290dGh1cnUiLCJpYXQiOjE2NzgxNjAyMzd9.35O7EfIYtQ6aRicuDTR_P5WWdgKeIOdznrLz9OsRc_Q
###

GET http://localhost:3005/user/followers/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJhbHVfa290dGh1cnUiLCJpYXQiOjE2NzgxNjAyMzd9.35O7EfIYtQ6aRicuDTR_P5WWdgKeIOdznrLz9OsRc_Q
###
